import type { DecodedImage, ProcessResult } from '@/lib/types';
import { createCanvas } from '@/lib/image/process';
import { canvasToBlob } from '@/lib/image/format';
import { clearCanvas } from '@/lib/image/transparent';
import { buildIco } from '@/lib/image/ico';

export interface FaviconOptions {
  /** Include a 180px Apple touch icon. */
  appleTouchIcon: boolean;
  /** Include 192/512px manifest icons + site.webmanifest. */
  manifest: boolean;
  /** App short name written into the manifest. */
  appName: string;
  /** Bundle everything into a ZIP alongside the individual files. */
  zip: boolean;
}

export interface FaviconResult extends ProcessResult {
  label: string;
}

const PNG_SIZES = [16, 32, 48] as const;

function squareCanvas(decoded: DecodedImage): HTMLCanvasElement {
  const side = Math.max(1, Math.max(decoded.width, decoded.height));
  const { canvas, ctx } = createCanvas(side, side);
  clearCanvas(ctx, side, side);
  const dx = Math.round((side - decoded.width) / 2);
  const dy = Math.round((side - decoded.height) / 2);
  if (decoded.bitmap) ctx.drawImage(decoded.bitmap, dx, dy, decoded.width, decoded.height);
  else ctx.drawImage(decoded.image, dx, dy, decoded.width, decoded.height);
  return canvas;
}

async function renderPng(square: HTMLCanvasElement, size: number): Promise<Blob> {
  const { canvas, ctx } = createCanvas(size, size);
  ctx.imageSmoothingEnabled = true;
  ctx.imageSmoothingQuality = 'high';
  ctx.drawImage(square, 0, 0, size, size);
  const blob = await canvasToBlob(canvas, { format: 'png' });
  canvas.width = 0;
  canvas.height = 0;
  return blob;
}

/**
 * Generate a complete favicon package: multi-size favicon.ico, PNG sizes,
 * an Apple touch icon, a web-manifest with maskable icons, and an optional
 * ZIP bundle. Everything is rendered locally on canvas.
 */
export async function makeFavicon(
  files: DecodedImage[],
  options: FaviconOptions,
): Promise<FaviconResult[]> {
  const decoded = files[0];
  const square = squareCanvas(decoded);
  const results: FaviconResult[] = [];
  const appName = (options.appName || 'My App').slice(0, 60);

  try {
    for (const size of PNG_SIZES) {
      const blob = await renderPng(square, size);
      results.push({
        blob,
        format: 'png',
        name: `favicon-${size}x${size}.png`,
        label: `PNG · ${size}×${size}`,
        originalSize: decoded.file.size,
      });
    }

    // The .ico bundles 16/32/48 — reuse freshly rendered PNGs for sharpness.
    const icoParts: { size: number; blob: Blob }[] = [];
    for (const size of PNG_SIZES) {
      icoParts.push({ size, blob: await renderPng(square, size) });
    }
    results.push({
      blob: await buildIco(icoParts),
      format: 'ico',
      name: 'favicon.ico',
      label: 'ICO · 16/32/48',
      originalSize: decoded.file.size,
    });

    if (options.appleTouchIcon) {
      results.push({
        blob: await renderPng(square, 180),
        format: 'png',
        name: 'apple-touch-icon.png',
        label: 'PNG · 180×180 (Apple)',
        originalSize: decoded.file.size,
      });
    }

    let manifestText: string | null = null;
    if (options.manifest) {
      for (const size of [192, 512] as const) {
        results.push({
          blob: await renderPng(square, size),
          format: 'png',
          name: `icon-${size}x${size}.png`,
          label: `PNG · ${size}×${size} (manifest)`,
          originalSize: decoded.file.size,
        });
      }
      manifestText = JSON.stringify(
        {
          name: appName,
          short_name: appName,
          icons: [
            { src: '/icon-192x192.png', sizes: '192x192', type: 'image/png' },
            { src: '/icon-512x512.png', sizes: '512x512', type: 'image/png' },
            { src: '/icon-512x512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
          ],
          theme_color: '#ffffff',
          background_color: '#ffffff',
          display: 'standalone',
        },
        null,
        2,
      );
      results.push({
        blob: new Blob([manifestText], { type: 'application/manifest+json' }),
        format: 'json',
        name: 'site.webmanifest',
        label: 'Web manifest',
      });
    }

    if (options.zip) {
      const { default: JSZip } = await import('jszip');
      const zip = new JSZip();
      for (const r of results) {
        zip.file(r.name, r.blob);
      }
      const html =
        '<!-- Favicon package generated by Piclizer -->\n' +
        '<link rel="icon" href="/favicon.ico" sizes="any">\n' +
        '<link rel="icon" href="/favicon-32x32.png" type="image/png" sizes="32x32">\n' +
        '<link rel="apple-touch-icon" href="/apple-touch-icon.png">\n' +
        '<link rel="manifest" href="/site.webmanifest">\n';
      zip.file('favicon-snippet.html', html);
      const zipBlob = await zip.generateAsync({ type: 'blob' });
      results.push({
        blob: zipBlob,
        format: 'zip',
        name: 'favicon-package.zip',
        label: 'ZIP bundle + HTML snippet',
      });
    }

    return results;
  } finally {
    square.width = 0;
    square.height = 0;
  }
}
