import {
  Activity,
  AppWindow,
  ArrowDownAZ,
  Binary,
  Braces,
  Cake,
  CalendarClock,
  CalendarDays,
  CaseSensitive,
  CloudFog,
  Calculator,
  Code,
  CodeXml,
  BookOpen,
  Coins,
  Combine,
  Contrast,
  Copy,
  Crop,
  Database,
  Droplets,
  Eraser,
  FileCode,
  FileDigit,
  FileJson,
  FilePen,
  FileSearch,
  FileSpreadsheet,
  FileMinus,
  FileOutput,
  FilePlus,
  FileText,
  FileType,
  FileType2,
  Fingerprint,
  Globe,
  Grid2x2,
  House,
  IdCard,
  Images,
  KeyRound,
  Landmark,
  Layers,
  Monitor,
  PanelTop,
  PenLine,
  Printer,
  Receipt,
  Sigma,
  Wallet,
  ZoomIn,
  ScanText,
  SlidersHorizontal,
  Squircle,
  SunMedium,
  TextSearch,
  Timer,
  Waypoints,
  FlipHorizontal,
  FlipVertical,
  Gauge,
  GitCompare,
  GraduationCap,
  Grid3X3,
  HandCoins,
  Hash,
  ImageDown,
  Link,
  Link2,
  ListOrdered,
  ListX,
  Lock,
  Paintbrush,
  Palette,
  Pencil,
  Percent,
  Pipette,
  Regex,
  Repeat,
  RotateCw,
  Ruler,
  Scaling,
  Scissors,
  Shield,
  Space,
  SpellCheck,
  Stamp,
  Tag,
  TextQuote,
  TrendingUp,
  Type,
  Unlock,
  type LucideIcon,
} from 'lucide-react';

/** Central icon registry — maps registry icon names to lucide icons. */
export const TOOL_ICONS: Record<string, LucideIcon> = {
  // image tools
  gauge: Gauge,
  scaling: Scaling,
  crop: Crop,
  rotate: RotateCw,
  'flip-horizontal': FlipHorizontal,
  'flip-vertical': FlipVertical,
  repeat: Repeat,
  'file-text': FileText,
  merge: Combine,
  grid: Grid3X3,
  pipette: Pipette,
  palette: Palette,
  grayscale: Droplets,
  stamp: Stamp,
  // categories
  pencil: Pencil,
  'file-pdf': FileType2,
  type: Type,
  calculator: Calculator,
  code: Code,
  // pdf tools
  'file-plus': FilePlus,
  'file-minus': FileMinus,
  'file-output': FileOutput,
  scissors: Scissors,
  'list-ordered': ListOrdered,
  lock: Lock,
  unlock: Unlock,
  'image-down': ImageDown,
  hash: Hash,
  // text tools
  'spell-check': SpellCheck,
  space: Space,
  'case-sensitive': CaseSensitive,
  eraser: Eraser,
  'text-quote': TextQuote,
  'flip-horizontal-2': FlipHorizontal,
  'list-x': ListX,
  link: Link,
  'link-2': Link2,
  'git-compare': GitCompare,
  // calculators
  cake: Cake,
  activity: Activity,
  percent: Percent,
  'trending-up': TrendingUp,
  'calendar-days': CalendarDays,
  ruler: Ruler,
  tag: Tag,
  'graduation-cap': GraduationCap,
  'hand-coins': HandCoins,
  coins: Coins,
  // new image tools
  'id-card': IdCard,
  'pen-line': PenLine,
  // effect tools
  blur: CloudFog,
  pixelate: Grid2x2,
  brightness: SunMedium,
  'sliders-h': SlidersHorizontal,
  squircle: Squircle,
  'file-search': FileSearch,
  'arrow-down-a-z': ArrowDownAZ,
  'text-search': TextSearch,
  'file-spreadsheet': FileSpreadsheet,
  waypoints: Waypoints,
  'calendar-clock': CalendarClock,
  timer: Timer,
  contrast: Contrast,
  'file-digit': FileDigit,
  'file-pen': FilePen,
  images: Images,
  // developer tools
  'key-round': KeyRound,
  database: Database,
  'file-json': FileJson,
  'book-open': BookOpen,
  fingerprint: Fingerprint,
  shield: Shield,
  braces: Braces,
  'code-xml': CodeXml,
  'file-code': FileCode,
  paintbrush: Paintbrush,
  regex: Regex,
  binary: Binary,
  // expansion tools
  'app-window': AppWindow,
  'zoom-in': ZoomIn,
  printer: Printer,
  layers: Layers,
  'panel-top': PanelTop,
  globe: Globe,
  monitor: Monitor,
  copy: Copy,
  landmark: Landmark,
  house: House,
  wallet: Wallet,
  receipt: Receipt,
  sigma: Sigma,
};

export function ToolIcon({ name, className }: { name: string; className?: string }) {
  const Icon = TOOL_ICONS[name] ?? Palette;
  return <Icon className={className} aria-hidden="true" />;
}
