import {
  Activity,
  Binary,
  Braces,
  Cake,
  CalendarDays,
  Camera,
  CaseSensitive,
  Calculator,
  Clock,
  Code,
  CodeXml,
  Coins,
  Combine,
  Crop,
  Droplets,
  Eraser,
  FileCode,
  FileMinus,
  FileOutput,
  FilePlus,
  FileText,
  FileType2,
  Fingerprint,
  FlipHorizontal,
  FlipVertical,
  Gauge,
  GitCompare,
  GraduationCap,
  Grid3X3,
  HandCoins,
  Hash,
  ImageDown,
  KeyRound,
  Link,
  Link2,
  ListOrdered,
  ListX,
  Lock,
  Paintbrush,
  Palette,
  Pencil,
  PenLine,
  Percent,
  Pipette,
  QrCode,
  Regex,
  Repeat,
  RotateCw,
  Ruler,
  Scaling,
  ScanText,
  Scissors,
  Shield,
  Space,
  SpellCheck,
  Stamp,
  Tag,
  TextQuote,
  TrendingUp,
  Type,
  Unlock,
  UserCheck,
  type LucideIcon,
} from 'lucide-react';

/** Central icon registry — maps registry icon names to lucide icons. */
export const TOOL_ICONS: Record<string, LucideIcon> = {
  // image tools
  gauge: Gauge,
  scaling: Scaling,
  crop: Crop,
  rotate: RotateCw,
  'flip-horizontal': FlipHorizontal,
  'flip-vertical': FlipVertical,
  repeat: Repeat,
  'file-text': FileText,
  merge: Combine,
  grid: Grid3X3,
  pipette: Pipette,
  palette: Palette,
  grayscale: Droplets,
  stamp: Stamp,
  'user-check': UserCheck,
  'pen-tool': PenLine,
  // categories
  pencil: Pencil,
  'file-pdf': FileType2,
  type: Type,
  calculator: Calculator,
  code: Code,
  // pdf tools
  'file-plus': FilePlus,
  'file-minus': FileMinus,
  'file-output': FileOutput,
  scissors: Scissors,
  'list-ordered': ListOrdered,
  lock: Lock,
  unlock: Unlock,
  'image-down': ImageDown,
  hash: Hash,
  // text tools
  'spell-check': SpellCheck,
  space: Space,
  'case-sensitive': CaseSensitive,
  eraser: Eraser,
  'text-quote': TextQuote,
  'flip-horizontal-2': FlipHorizontal,
  'list-x': ListX,
  link: Link,
  'link-2': Link2,
  'git-compare': GitCompare,
  'scan-text': ScanText,
  // calculators
  cake: Cake,
  activity: Activity,
  percent: Percent,
  'trending-up': TrendingUp,
  'calendar-days': CalendarDays,
  ruler: Ruler,
  tag: Tag,
  'graduation-cap': GraduationCap,
  'hand-coins': HandCoins,
  coins: Coins,
  // developer tools
  fingerprint: Fingerprint,
  shield: Shield,
  braces: Braces,
  'code-xml': CodeXml,
  'file-code': FileCode,
  paintbrush: Paintbrush,
  regex: Regex,
  binary: Binary,
  'key-round': KeyRound,
  clock: Clock,
  'qr-code': QrCode,
  camera: Camera,
};

export function ToolIcon({ name, className }: { name: string; className?: string }) {
  const Icon = TOOL_ICONS[name] ?? Palette;
  return <Icon className={className} aria-hidden="true" />;
}
