/** One-off content migration: adds strings for the new tools + guides. Idempotent. */
import { readFileSync, writeFileSync } from 'node:fs';

const EN = 'messages/en.json';
const AR = 'messages/ar.json';

const en = JSON.parse(readFileSync(EN, 'utf8'));
const ar = JSON.parse(readFileSync(AR, 'utf8'));

function setPath(obj, path, value) {
  const parts = path.split('.');
  let node = obj;
  for (let i = 0; i < parts.length - 1; i += 1) {
    if (typeof node[parts[i]] !== 'object' || node[parts[i]] === null) node[parts[i]] = {};
    node = node[parts[i]];
  }
  node[parts[parts.length - 1]] = value;
}

/* ------------------------------------------------------------------ tools */

const TOOLS_EN = {
  'heic-to-jpg': {
    name: 'HEIC to JPG',
    short: 'Convert iPhone HEIC photos to JPG.',
    description: 'Convert HEIC to JPG online for free. Turn iPhone photos into universal JPG files entirely in your browser — no upload needed.',
    intro: 'iPhone photos save as HEIC, which many apps and websites still reject. Convert them to JPG — the format that works everywhere — with control over quality and background, all processed locally on your device.',
    howTo: ['Add one or more HEIC or HEIF photos from your iPhone.', 'Set the output quality (85–92% is ideal for sharing).', 'Press Convert to JPG.', 'Download your JPG files, ready to share anywhere.'],
    faqs: [
      { q: 'Why convert HEIC to JPG?', a: 'HEIC is efficient but poorly supported outside Apple devices. JPG opens everywhere — on the web, in email, on Windows and Android.' },
      { q: 'Will my photos be uploaded?', a: 'No. Conversion uses a decoder running inside your browser. Your photos never leave your device.' },
      { q: 'Does converting lose quality?', a: 'JPG is lossy, so keep quality at 90% or above for results visually identical to the original.' },
      { q: 'Are portrait orientation and HDR preserved?', a: 'Yes. EXIF orientation is applied during decoding so photos never come out sideways, and HDR tone is carried into the JPG.' },
      { q: 'Can I convert several photos at once?', a: 'Yes — add up to 10 HEIC files and convert them as a batch.' },
    ],
  },
  'heic-to-png': {
    name: 'HEIC to PNG',
    short: 'Convert iPhone HEIC photos to PNG.',
    description: 'Convert HEIC to PNG online for free. Lossless-quality conversion of iPhone photos, processed privately in your browser.',
    intro: 'Need your iPhone photo in a lossless format for editing or graphics work? Convert HEIC to PNG with pixel-perfect fidelity, straight in your browser.',
    howTo: ['Add your HEIC or HEIF photos.', 'Press Convert to PNG.', 'Compare the original and converted sizes.', 'Download your PNG files.'],
    faqs: [
      { q: 'Why is the PNG larger than my HEIC?', a: 'PNG is lossless and stores every pixel exactly, while HEIC is heavily compressed — larger files are normal.' },
      { q: 'Is transparency supported?', a: 'Yes. If the source has an alpha channel it is preserved in the PNG output.' },
      { q: 'Are my photos uploaded?', a: 'No — decoding and conversion happen entirely on your device.' },
      { q: 'Can I batch convert?', a: 'Yes, up to 10 files at once.' },
    ],
  },
  'image-to-exact-kb': {
    name: 'Image to Exact KB',
    short: 'Compress any image to an exact file size.',
    description: 'Compress an image to an exact size online — 100 KB, 200 KB, 50 KB. Smart quality + dimension tuning, free and private in your browser.',
    intro: 'Job portals, exam forms and uploads often demand an exact size like “under 100 KB”. Set your target and Piclizer searches quality levels — shrinking dimensions only if it must — to land precisely on it.',
    howTo: ['Add your image (JPG, PNG, WebP or iPhone HEIC).', 'Type the target size in KB, e.g. 100.', 'Choose the output format.', 'Press Compress and download the exactly-sized file.'],
    faqs: [
      { q: 'How does it hit the exact size?', a: 'It probes several quality levels at full resolution, then bisects to the best quality that fits. Only if that fails does it step dimensions down gradually.' },
      { q: 'Will my image be resized?', a: 'Only when necessary. Resolution is preserved whenever the target can be met with quality tuning alone.' },
      { q: 'What if the target is impossibly small?', a: 'The tool returns the smallest file it could produce and tells you honestly that the target could not be met.' },
      { q: 'Which format gives the smallest file?', a: 'Usually WebP, then JPG. PNG is lossless and cannot reach very small targets for photos.' },
      { q: 'Are my images uploaded?', a: 'Never. Every trial encode runs in your browser.' },
    ],
  },
  'background-remover': {
    name: 'Background Remover',
    short: 'Erase solid backgrounds automatically.',
    description: 'Remove image backgrounds online for free. Chroma-key removal for solid backgrounds with feathered edges, exported as transparent PNG — in your browser.',
    intro: 'Cut out products, logos and signatures photographed on solid backgrounds. The tool samples the background colour, removes it with soft feathered edges, and hands you a transparent PNG.',
    howTo: ['Add a photo with a fairly solid background.', 'Choose Auto-detect or pure White background.', 'Tune Tolerance until the background disappears.', 'Soften edges with Feather, then download the PNG.'],
    faqs: [
      { q: 'When does it work best?', a: 'On solid or smoothly graduated backgrounds — product shots, documents, signatures. Busy multi-colour scenes need manual editing software.' },
      { q: 'What does Tolerance do?', a: 'It sets how close a pixel must be to the background colour to become transparent. Raise it for off-white or shadowed backgrounds.' },
      { q: 'Is this AI segmentation?', a: 'No — it is a transparent chroma-key algorithm running locally. It is honest about that: no uploads, no AI server, instant results.' },
      { q: 'Which format is exported?', a: 'Always PNG, because it is the format that supports transparency.' },
    ],
  },
  'passport-photo-maker': {
    name: 'Passport Photo Maker',
    short: 'Make print-ready ID and passport photos.',
    description: 'Make passport photos online for free. Exact 35×45 mm, 2×2 inch and other ID sizes at 300/600 DPI — cropped and exported in your browser.',
    intro: 'Turn any portrait into a correctly sized ID photo. Pick your country’s dimensions, choose print resolution, and get a file with the exact pixel size photo studios and online forms expect.',
    howTo: ['Add a front-facing portrait photo.', 'Choose the ID size preset (e.g. 35×45 mm).', 'Pick 300 or 600 DPI print resolution.', 'Press Make photo and download the print-ready file.'],
    faqs: [
      { q: 'Which sizes are supported?', a: '35×45 mm (most passports), 30×40 mm, 33×48 mm, 2×2 inch (US visa) and 40×60 mm.' },
      { q: 'What resolution will the file be?', a: 'At 300 DPI a 35×45 mm photo is 413×531 px; at 600 DPI it doubles. Both are shown before you export.' },
      { q: 'Does it check official photo rules?', a: 'No — it handles exact sizing only. Always verify background, expression and recency rules with your issuing authority.' },
      { q: 'Are my portrait photos uploaded?', a: 'No. Everything is cropped and rendered on your device.' },
    ],
  },
  'signature-maker': {
    name: 'Signature Maker',
    short: 'Turn a photo of your signature transparent.',
    description: 'Make a transparent signature online for free. Convert a photo of your handwritten signature into a clean PNG stamp for documents — in your browser.',
    intro: 'Sign paper once, use it everywhere. Photograph your signature, and this tool strips the paper background, applies your ink colour and auto-crops to a tidy transparent PNG for PDFs and forms.',
    howTo: ['Photograph your signature on plain white paper in good light.', 'Upload the photo.', 'Adjust Threshold until the paper disappears but strokes stay solid.', 'Pick an ink colour and download the transparent PNG.'],
    faqs: [
      { q: 'How do I photograph my signature?', a: 'Use dark ink on plain white paper, in bright even light, holding the camera directly above. Sharp, evenly lit photos give the cleanest result.' },
      { q: 'What does Threshold do?', a: 'It decides which pixels count as ink. Too high keeps paper noise; too low eats thin strokes. Aim for solid strokes with a clean background.' },
      { q: 'Can I change the ink colour?', a: 'Yes — black, blue and red presets plus any custom colour.' },
      { q: 'Is a PNG signature legally valid?', a: 'That depends on your jurisdiction and the document. The tool only creates the image; check what your recipient accepts.' },
    ],
  },
  'image-ocr': {
    name: 'Image to Text (OCR)',
    short: 'Extract text from photos and screenshots.',
    description: 'Extract text from images online for free. OCR for photos, screenshots and scans in English and Arabic — processed privately in your browser.',
    intro: 'Turn pictures of text into editable text. Receipts, screenshots, whiteboards and scanned pages are recognised on your device with support for English, Arabic or both.',
    howTo: ['Add up to 5 images (JPG, PNG, WebP or HEIC).', 'Choose the text language: English, Arabic or both.', 'Press Extract text and wait for recognition.', 'Copy the result or download it as a .txt file.'],
    faqs: [
      { q: 'How accurate is the OCR?', a: 'Very good on clear, high-contrast, horizontal text. Blurry, rotated or highly stylised text recognises less reliably.' },
      { q: 'Does it support Arabic?', a: 'Yes — Arabic, English, or a bilingual mode for mixed documents.' },
      { q: 'Are my images uploaded for recognition?', a: 'No. The Tesseract engine and language files run inside your browser; only those program files are downloaded once from a CDN.' },
      { q: 'Why does the first run take a moment?', a: 'The recognition engine and language data (a few MB) download on first use, then are cached for instant later runs.' },
    ],
  },
  'pdf-to-text': {
    name: 'PDF to Text',
    short: 'Extract all text from a PDF as .txt.',
    description: 'Convert PDF to text online for free. Extract every page’s text into a clean .txt file with page markers — processed privately in your browser.',
    intro: 'Get the words out of your PDF. Every page’s text is extracted locally and packaged as a tidy .txt file with page markers — perfect for quoting, archiving or feeding into other tools.',
    howTo: ['Add up to 5 PDF files.', 'Press Extract text.', 'Preview the character and page counts.', 'Download each .txt file, or all at once as a ZIP.'],
    faqs: [
      { q: 'Does it work on scanned PDFs?', a: 'Scanned pages are pictures of text, so no embedded text exists to extract. Use the PDF OCR tool for those.' },
      { q: 'Is the layout preserved?', a: 'Text comes out in reading order with page markers, but exact visual layout (columns, tables) is not reconstructed.' },
      { q: 'What about password-protected PDFs?', a: 'Unlock them first with the PDF Unlock tool, then extract.' },
      { q: 'Are my documents uploaded?', a: 'No. Extraction runs entirely in your browser.' },
    ],
  },
  'pdf-to-word': {
    name: 'PDF to Word',
    short: 'Convert PDF pages into editable Word files.',
    description: 'Convert PDF to Word online for free. Turn PDF pages into editable .doc files with headings and page breaks — generated privately in your browser.',
    intro: 'Need to edit a PDF’s content? Convert each document into an editable Word (.doc) file with page headings and page breaks, ready to open in Word, LibreOffice or Google Docs.',
    howTo: ['Add up to 5 PDF files.', 'Press Convert to Word.', 'Check the page counts.', 'Download each .doc file, or all at once as a ZIP.'],
    faqs: [
      { q: 'What Word format is produced?', a: 'A Word-compatible .doc file that opens in Microsoft Word, LibreOffice and Google Docs for editing.' },
      { q: 'Will tables and images transfer?', a: 'Text transfers cleanly; complex tables, images and exact styling do not — this is a text-first conversion done fully offline.' },
      { q: 'Does it work on scanned PDFs?', a: 'Not directly — run the PDF OCR tool first, or use it on text-based PDFs.' },
      { q: 'Are my documents uploaded?', a: 'Never. The whole conversion happens on your device.' },
    ],
  },
  'pdf-ocr': {
    name: 'PDF OCR',
    short: 'Recognise text in scanned PDFs.',
    description: 'OCR scanned PDFs online for free. Render each page locally and recognise English or Arabic text into a .txt file — private, in-browser processing.',
    intro: 'Your scanner produces pictures, not text. This tool renders each page and recognises the words with an on-device OCR engine, giving you selectable, copyable text.',
    howTo: ['Add up to 3 scanned PDFs.', 'Choose English, Arabic or both.', 'Press Extract text and follow the per-page progress.', 'Download the recognised .txt files.'],
    faqs: [
      { q: 'How is this different from PDF to Text?', a: 'PDF to Text reads embedded text instantly. PDF OCR re-reads page images with character recognition, so it works on scans but is slower.' },
      { q: 'Why is there a 30-page limit?', a: 'Rendering plus recognition is heavy work; the cap keeps your browser tab fast and stable.' },
      { q: 'Is recognition done online?', a: 'No. Pages render with pdf.js and text is recognised by Tesseract inside your browser. Only the engine files download once from a CDN.' },
      { q: 'How can I improve accuracy?', a: 'Use straight, high-resolution scans (200 DPI or more) with clean contrast.' },
    ],
  },
  'jwt-decoder': {
    name: 'JWT Decoder',
    short: 'Decode and verify JSON Web Tokens.',
    description: 'Decode JWT tokens online for free. Inspect header and payload, check expiry, and verify HS256 signatures — offline in your browser, tokens never leave your device.',
    intro: 'Paste any JSON Web Token to read its header and payload instantly, see expiry in plain language, and verify HMAC signatures with your secret — all offline, nothing transmitted.',
    howTo: ['Paste the JWT into the token box.', 'Read the decoded header and payload.', 'Check the expiry verdict.', 'Optionally enter your HMAC secret to verify the signature.'],
    faqs: [
      { q: 'Is my token sent anywhere?', a: 'No. Decoding is pure base64url math in your browser, and even signature verification uses local Web Crypto.' },
      { q: 'Which algorithms can be verified?', a: 'HS256, HS384 and HS512 with a shared secret. RS256/ES256 need public-key handling beyond a quick decoder.' },
      { q: 'Why does it say “expired”?', a: 'The exp claim is compared against your device clock. Check your clock if a fresh token looks expired.' },
      { q: 'Can it create or sign tokens?', a: 'No — it is a decoder and verifier only, which keeps secrets out of the page.' },
    ],
  },
  'sql-formatter': {
    name: 'SQL Formatter',
    short: 'Beautify and minify SQL queries.',
    description: 'Format SQL online for free. Beautify queries with indentation and keyword casing, or minify them — processed instantly and privately in your browser.',
    intro: 'Turn one-line SQL blobs into readable queries. Clauses break onto their own lines, joins and conditions indent cleanly, and keywords follow your casing choice.',
    howTo: ['Paste your SQL query.', 'Choose keyword casing and indent size.', 'Press Format (or Minify for one line).', 'Copy the result or download it as .sql.'],
    faqs: [
      { q: 'Is my SQL uploaded?', a: 'No. Formatting is a small local algorithm — your queries never leave the tab.' },
      { q: 'Are strings and comments safe?', a: 'Yes. String literals and comments are tokenised first, so keywords inside them are never altered.' },
      { q: 'Which dialects are supported?', a: 'Standard SQL shared by Postgres, MySQL, SQLite and SQL Server. Dialect-specific procedural blocks format on a best-effort basis.' },
      { q: 'What does Minify do?', a: 'It strips comments and collapses whitespace to a single line for embedding or logging.' },
    ],
  },
  'yaml-formatter': {
    name: 'YAML Formatter',
    short: 'Validate, format and convert YAML.',
    description: 'Format YAML online for free. Validate syntax with exact error messages, re-indent, sort keys and convert YAML to JSON — privately in your browser.',
    intro: 'Fix broken YAML configs fast. Validate with precise error locations, re-indent consistently, sort keys for clean diffs, or convert straight to JSON.',
    howTo: ['Paste your YAML.', 'Choose indent size and optional key sorting.', 'Press Format — or Convert to JSON.', 'Copy the output or download it.'],
    faqs: [
      { q: 'How are errors reported?', a: 'The parser returns the exact line and reason, e.g. bad indentation or a stray tab, which YAML forbids.' },
      { q: 'Does formatting change my data?', a: 'No. Only whitespace and (optionally) key order change; values stay identical.' },
      { q: 'Can it convert YAML to JSON?', a: 'Yes — one click produces equivalent JSON with 2-space indentation.' },
      { q: 'Is my config uploaded?', a: 'Never. Parsing runs locally in your browser.' },
    ],
  },
  'markdown-formatter': {
    name: 'Markdown Formatter',
    short: 'Prettify Markdown documents.',
    description: 'Format Markdown online for free. Normalise headings, lists and prose wrapping with Prettier — running locally in your browser, files stay private.',
    intro: 'Make Markdown consistent: uniform lists, tidy headings, and prose wrapped to your line width — powered by Prettier, running entirely on your device.',
    howTo: ['Paste your Markdown.', 'Choose line width and prose-wrap behaviour.', 'Press Format.', 'Copy the result or download it as .md.'],
    faqs: [
      { q: 'What gets normalised?', a: 'List markers, heading spacing, emphasis style, code fences and line wrapping — the same output Prettier gives in editors.' },
      { q: 'Will it change my words?', a: 'No. Only formatting changes; text content is untouched.' },
      { q: 'What is prose wrap?', a: 'Whether long paragraphs are re-wrapped to your line width, left as-is, or kept on single lines.' },
      { q: 'Is my document uploaded?', a: 'No. Prettier loads into your browser and formats locally.' },
    ],
  },
};

const TOOLS_AR = {
  'heic-to-jpg': {
    name: 'تحويل HEIC إلى JPG',
    short: 'حوّل صور الايفون HEIC إلى JPG.',
    description: 'حوّل HEIC إلى JPG مجانًا عبر الإنترنت. حوّل صور الايفون إلى ملفات JPG تعمل في كل مكان — داخل متصفحك بدون رفع.',
    intro: 'صور الايفون تُحفظ بصيغة HEIC التي لا تقبلها كثير من التطبيقات والمواقع. حوّلها إلى JPG — الصيغة التي تعمل في كل مكان — مع التحكم بالجودة، وكل المعالجة تتم محليًا على جهازك.',
    howTo: ['أضف صورة أو أكثر بصيغة HEIC أو HEIF من الايفون.', 'اختر جودة الإخراج (85–92% مثالية للمشاركة).', 'اضغط تحويل إلى JPG.', 'حمّل ملفات JPG جاهزة للمشاركة في أي مكان.'],
    faqs: [
      { q: 'لماذا أحوّل HEIC إلى JPG؟', a: 'صيغة HEIC فعالة لكن دعمها ضعيف خارج أجهزة آبل. صيغة JPG تعمل في كل مكان — الويب والبريد وويندوز وأندرويد.' },
      { q: 'هل تُرفع صوري إلى أي مكان؟', a: 'لا. التحويل يتم بواسطة أداة فك ترميز تعمل داخل متصفحك، ولا تغادر صورك جهازك أبدًا.' },
      { q: 'هل يفقد التحويل الجودة؟', a: 'صيغة JPG مضغوطة، لذا حافظ على جودة 90% أو أعلى لنتائج مطابقة بصريًا للأصل.' },
      { q: 'هل يُحافظ على اتجاه الصورة؟', a: 'نعم. يُطبَّق اتجاه EXIF أثناء فك الترميز فلا تظهر الصور مقلوبة أو جانبية.' },
      { q: 'هل يمكن تحويل عدة صور دفعة واحدة؟', a: 'نعم — أضف حتى 10 ملفات HEIC وحوّلها معًا.' },
    ],
  },
  'heic-to-png': {
    name: 'تحويل HEIC إلى PNG',
    short: 'حوّل صور الايفون HEIC إلى PNG.',
    description: 'حوّل HEIC إلى PNG مجانًا عبر الإنترنت. تحويل صور الايفون بجودة كاملة دون فقدان — بخصوصية تامة داخل متصفحك.',
    intro: 'تحتاج صورة الايفون بصيغة غير مضغوطة للتحرير أو التصميم؟ حوّل HEIC إلى PNG بدقة كاملة مباشرة في متصفحك.',
    howTo: ['أضف صور HEIC أو HEIF.', 'اضغط تحويل إلى PNG.', 'قارن بين الحجم الأصلي والمحوَّل.', 'حمّل ملفات PNG.'],
    faqs: [
      { q: 'لماذا ملف PNG أكبر من HEIC؟', a: 'صيغة PNG تحفظ كل بكسل بدقة دون ضغط، بينما HEIC مضغوطة بشدة — فالملفات الأكبر أمر طبيعي.' },
      { q: 'هل تُحفظ الشفافية؟', a: 'نعم. إذا كان المصدر يحتوي قناة شفافية فستُحفظ في ملف PNG.' },
      { q: 'هل تُرفع صوري؟', a: 'لا — فك الترميز والتحويل يتمّان بالكامل على جهازك.' },
      { q: 'هل يدعم التحويل الجماعي؟', a: 'نعم، حتى 10 ملفات دفعة واحدة.' },
    ],
  },
  'image-to-exact-kb': {
    name: 'ضغط الصورة إلى حجم محدد',
    short: 'اضغط أي صورة إلى حجم دقيق بالكيلوبايت.',
    description: 'اضغط الصورة إلى حجم محدد عبر الإنترنت — 100KB أو 200KB أو 50KB. ضبط ذكي للجودة والأبعاد، مجانًا وبخصوصية داخل متصفحك.',
    intro: 'مواقع التوظيف ونماذج التقديم تطلب حجمًا دقيقًا مثل "أقل من 100KB". حدّد هدفك وسيبحث Piclizer عن أفضل جودة تناسبه — ولا يصغّر الأبعاد إلا عند الضرورة.',
    howTo: ['أضف صورتك (JPG أو PNG أو WebP أو HEIC).', 'اكتب الحجم المستهدف بالكيلوبايت، مثل 100.', 'اختر صيغة الإخراج.', 'اضغط ضغط وحمّل الملف بالحجم المطلوب تمامًا.'],
    faqs: [
      { q: 'كيف يصل إلى الحجم الدقيق؟', a: 'يجرّب عدة مستويات جودة بالدقة الكاملة ثم يضيّق البحث على أفضل جودة تناسب الهدف، ولا يصغّر الأبعاد إلا إذا تعذّر ذلك.' },
      { q: 'هل ستتغير أبعاد صورتي؟', a: 'فقط عند الضرورة. تُحفَظ الدقة الكاملة كلما أمكن تحقيق الهدف بضبط الجودة وحده.' },
      { q: 'ماذا لو كان الهدف مستحيلًا؟', a: 'تُعاد أصغر نسخة ممكنة مع إخبارك بوضوح أن الهدف لم يتحقق.' },
      { q: 'أي صيغة تعطي أصغر ملف؟', a: 'عادة WebP ثم JPG. أما PNG فغير مضغوطة ولا تصل لأحجام صغيرة جدًا مع الصور الفوتوغرافية.' },
      { q: 'هل تُرفع صوري؟', a: 'أبدًا. كل محاولات الترميز تعمل في متصفحك.' },
    ],
  },
  'background-remover': {
    name: 'إزالة خلفية الصورة',
    short: 'أزل الخلفيات السادة تلقائيًا.',
    description: 'أزل خلفية الصورة مجانًا عبر الإنترنت. إزالة بخوارزمية محلية للخلفيات السادة مع حواف ناعمة، وتصدير PNG شفاف — داخل متصفحك.',
    intro: 'اعزل المنتجات والشعارات والتوقيعات المصورة على خلفيات سادة. تكتشف الأداة لون الخلفية وتزيله بحواف ناعمة وتمنحك ملف PNG شفافًا.',
    howTo: ['أضف صورة بخلفية سادة نسبيًا.', 'اختر التحديد التلقائي أو الأبيض النقي.', 'اضبط الحساسية حتى تختفي الخلفية.', 'نعّم الحواف ثم حمّل ملف PNG.'],
    faqs: [
      { q: 'متى تعمل بأفضل شكل؟', a: 'مع الخلفيات السادة أو المتدرجة بسلاسة — صور المنتجات والمستندات والتوقيعات. المشاهد المزدحمة متعددة الألوان تحتاج برامج تحرير يدوية.' },
      { q: 'ماذا تفعل الحساسية؟', a: 'تحدد مدى قرب اللون من لون الخلفية ليصبح شفافًا. ارفعها للخلفيات غير البيضاء تمامًا أو ذات الظلال.' },
      { q: 'هل هذه تقنية ذكاء اصطناعي؟', a: 'لا — بل خوارزمية محلية شفافة تعمل دون رفع أو خوادم، وتعطي نتائج فورية.' },
      { q: 'ما صيغة التصدير؟', a: 'دائمًا PNG لأنها الصيغة التي تدعم الشفافية.' },
    ],
  },
  'passport-photo-maker': {
    name: 'صانع صور الجواز',
    short: 'اصنع صور هوية وجواز جاهزة للطباعة.',
    description: 'اصنع صورة جواز مجانًا عبر الإنترنت. مقاسات دقيقة 35×45 مم و2×2 إنش وغيرها بدقة 300/600 DPI — قص وتصدير داخل متصفحك.',
    intro: 'حوّل أي صورة شخصية إلى صورة هوية بالمقاس الصحيح. اختر مقاس بلدك ودقة الطباعة واحصل على ملف بالأبعاد الدقيقة التي تتوقعها الاستوديوهات والنماذج الإلكترونية.',
    howTo: ['أضف صورة شخصية أمامية.', 'اختر مقاس الهوية (مثل 35×45 مم).', 'اختر دقة الطباعة 300 أو 600 DPI.', 'اضغط إنشاء وحمّل الملف الجاهز للطباعة.'],
    faqs: [
      { q: 'ما المقاسات المدعومة؟', a: '35×45 مم (معظم الجوازات)، 30×40 مم، 33×48 مم، 2×2 إنش (تأشيرة أمريكا)، 40×60 مم.' },
      { q: 'ما دقة الملف الناتج؟', a: 'بدقة 300 DPI تكون صورة 35×45 مم بأبعاد 413×531 بكسل، وتتضاعف عند 600 DPI — وتظهر الأبعاد قبل التصدير.' },
      { q: 'هل تتحقق من الشروط الرسمية؟', a: 'لا — الأداة تضبط المقاس فقط. تحقق دائمًا من شروط الخلفية والملامح والحداثة لدى الجهة المُصدِرة.' },
      { q: 'هل تُرفع صوري الشخصية؟', a: 'لا. القص والعرض يتمّان بالكامل على جهازك.' },
    ],
  },
  'signature-maker': {
    name: 'صانع التوقيع',
    short: 'حوّل صورة توقيعك إلى ملف شفاف.',
    description: 'اصنع توقيعًا شفافًا مجانًا عبر الإنترنت. حوّل صورة توقيعك اليدوي إلى ختم PNG نظيف للمستندات — داخل متصفحك.',
    intro: 'وقّع على الورق مرة واحدة واستخدمه في كل مكان. صوّر توقيعك وستزيل الأداة خلفية الورق وتطبّق لون الحبر وتقص الناتج إلى ملف PNG شفاف للملفات والنماذج.',
    howTo: ['صوّر توقيعك على ورقة بيضاء بإضاءة جيدة.', 'ارفع الصورة.', 'اضبط العتبة حتى يختفي الورق وتبقى الخطوط واضحة.', 'اختر لون الحبر وحمّل ملف PNG الشفاف.'],
    faqs: [
      { q: 'كيف أصوّر توقيعي؟', a: 'استخدم حبرًا داكنًا على ورقة بيضاء سادة بإضاءة ساطعة متساوية، والكاميرا عمودية فوق الورقة مباشرة.' },
      { q: 'ماذا تفعل العتبة؟', a: 'تحدد أي البكسلات تُحتسب حبرًا. القيمة العالية تُبقي ضجيج الورق، والمنخفضة تأكل الخطوط الرفيعة.' },
      { q: 'هل يمكن تغيير لون الحبر؟', a: 'نعم — أسود وأزرق وأحمر جاهزة إضافة لأي لون مخصص.' },
      { q: 'هل التوقيع الإلكتروني مقبول قانونيًا؟', a: 'يعتمد على بلدك ونوع المستند. الأداة تنشئ الصورة فقط، فتحقق مما يقبله الطرف المستلم.' },
    ],
  },
  'image-ocr': {
    name: 'استخراج النص من الصور (OCR)',
    short: 'استخرج النص من الصور ولقطات الشاشة.',
    description: 'استخرج النص من الصور مجانًا عبر الإنترنت. تعرّف ضوئي على الصور واللقطات والمستندات بالعربية والإنجليزية — بخصوصية داخل متصفحك.',
    intro: 'حوّل صور النصوص إلى نص قابل للتحرير. تُتعرَّف الإيصالات واللقطات والسبورات والصفحات الممسوحة على جهازك بدعم العربية أو الإنجليزية أو both.',
    howTo: ['أضف حتى 5 صور (JPG أو PNG أو WebP أو HEIC).', 'اختر لغة النص: العربية أو الإنجليزية أو both.', 'اضغط استخراج النص وانتظر التعرّف.', 'انسخ النتيجة أو حمّلها كملف .txt.'],
    faqs: [
      { q: 'ما مدى دقة التعرّف؟', a: 'ممتازة مع النص الواضح عالي التباين والأفقي. النص الضبابي أو المائل أو المزخرف أقل موثوقية.' },
      { q: 'هل يدعم العربية؟', a: 'نعم — العربية أو الإنجليزية أو وضع ثنائي للمستندات المختلطة.' },
      { q: 'هل تُرفع صوري للتعرّف؟', a: 'لا. محرك Tesseract وملفات اللغة يعملان داخل متصفحك، ولا تُنزَّل منهما سوى ملفات البرنامج مرة واحدة.' },
      { q: 'لماذا يتأخر التشغيل الأول؟', a: 'لأن محرك التعرّف وبيانات اللغة (بضعة ميغابايت) تُنزَّل أول مرة ثم تُحفظ للتشغيل الفوري لاحقًا.' },
    ],
  },
  'pdf-to-text': {
    name: 'تحويل PDF إلى نص',
    short: 'استخرج كل النصوص من PDF كملف .txt.',
    description: 'حوّل PDF إلى نص مجانًا عبر الإنترنت. استخرج نص كل صفحة إلى ملف .txt نظيف مع علامات الصفحات — بخصوصية داخل متصفحك.',
    intro: 'استخرج الكلمات من ملف PDF. يُستخرَج نص كل صفحة محليًا ويُجمَّع في ملف .txt مرتب مع علامات الصفحات — مثالي للاقتباس والأرشفة.',
    howTo: ['أضف حتى 5 ملفات PDF.', 'اضغط استخراج النص.', 'راجع عدد الأحرف والصفحات.', 'حمّل كل ملف .txt أو الكل دفعة واحدة كـ ZIP.'],
    faqs: [
      { q: 'هل يعمل مع ملفات PDF الممسوحة؟', a: 'الصفحات الممسوحة صور للنصوص فلا تحتوي نصًا مضمّنًا. استخدم أداة OCR لملفات PDF مع تلك الملفات.' },
      { q: 'هل يُحفَظ التنسيق؟', a: 'يخرج النص بترتيب القراءة مع علامات الصفحات، لكن التخطيط البصري الدقيق (الأعمدة والجداول) لا يُعاد بناؤه.' },
      { q: 'ماذا عن الملفات المحمية بكلمة مرور؟', a: 'أزل الحماية أولًا بأداة فك حماية PDF ثم استخرج النص.' },
      { q: 'هل تُرفع مستنداتي؟', a: 'لا. الاستخراج يتم بالكامل في متصفحك.' },
    ],
  },
  'pdf-to-word': {
    name: 'تحويل PDF إلى Word',
    short: 'حوّل صفحات PDF إلى ملفات Word قابلة للتحرير.',
    description: 'حوّل PDF إلى Word مجانًا عبر الإنترنت. حوّل صفحات PDF إلى ملفات .doc قابلة للتحرير مع العناوين وفواصل الصفحات — بخصوصية داخل متصفحك.',
    intro: 'تحتاج تحرير محتوى PDF؟ حوّل كل مستند إلى ملف Word (.doc) قابل للتحرير مع عناوين الصفحات وفواصلها، جاهز للفتح في Word أو LibreOffice أو مستندات Google.',
    howTo: ['أضف حتى 5 ملفات PDF.', 'اضغط تحويل إلى Word.', 'تحقق من عدد الصفحات.', 'حمّل كل ملف .doc أو الكل دفعة واحدة كـ ZIP.'],
    faqs: [
      { q: 'ما صيغة ملف Word الناتج؟', a: 'ملف .doc متوافق مع Word يفتح في Microsoft Word وLibreOffice ومستندات Google للتحرير.' },
      { q: 'هل تنتقل الجداول والصور؟', a: 'ينتقل النص بوضوح، أما الجداول المعقدة والصور والتنسيق الدقيق فلا — فالتحويل نصي ويعمل دون إنترنت.' },
      { q: 'هل يعمل مع الملفات الممسوحة؟', a: 'ليس مباشرة — استخدم أداة OCR أولًا، أو استخدمه مع ملفات PDF النصية.' },
      { q: 'هل تُرفع مستنداتي؟', a: 'أبدًا. التحويل كله يحدث على جهازك.' },
    ],
  },
  'pdf-ocr': {
    name: 'التعرّف الضوئي على PDF',
    short: 'تعرّف على النصوص في ملفات PDF الممسوحة.',
    description: 'تعرّف ضوئيًا على ملفات PDF الممسوحة مجانًا عبر الإنترنت. اعرض كل صفحة محليًا وتعرّف على النص العربي أو الإنجليزي في ملف .txt — بخصوصية داخل المتصفح.',
    intro: 'الماسح الضوئي ينتج صورًا لا نصوصًا. تعرض هذه الأداة كل صفحة وتتعرّف على الكلمات بمحرك يعمل على جهازك، فتمنحك نصًا قابلًا للتحديد والنسخ.',
    howTo: ['أضف حتى 3 ملفات PDF ممسوحة.', 'اختر العربية أو الإنجليزية أو both.', 'اضغط استخراج النص وتابع التقدم لكل صفحة.', 'حمّل ملفات .txt المتعرَّف عليها.'],
    faqs: [
      { q: 'ما الفرق عن تحويل PDF إلى نص؟', a: 'تحويل PDF إلى نص يقرأ النص المضمّن فورًا. أما OCR فيعيد قراءة صور الصفحات، فيعمل مع الملفات الممسوحة لكنه أبطأ.' },
      { q: 'لماذا الحد 30 صفحة؟', a: 'لأن العرض والتعرّف عمل ثقيل، والحد يحافظ على سرعة وثبات تبويب المتصفح.' },
      { q: 'هل التعرّف يتم عبر الإنترنت؟', a: 'لا. تُعرَض الصفحات محليًا ويتعرّف Tesseract داخل متصفحك، ولا تُنزَّل سوى ملفات المحرك مرة واحدة.' },
      { q: 'كيف أحسّن الدقة؟', a: 'استخدم مسحًا مستقيمًا عالي الدقة (200 DPI أو أكثر) بتباين نظيف.' },
    ],
  },
  'jwt-decoder': {
    name: 'فك تشفير JWT',
    short: 'فك رموز JWT وتحقق منها.',
    description: 'فك تشفير رموز JWT مجانًا عبر الإنترنت. افحص الترويسة والحمولة وتحقق من انتهاء الصلاحية وتواقيع HS256 — دون اتصال داخل متصفحك.',
    intro: 'الصق أي رمز JWT لقراءة ترويسته وحمولته فورًا، ومعرفة انتهاء الصلاحية بلغة واضحة، والتحقق من تواقيع HMAC بسرّك — كل ذلك دون اتصال ودون إرسال أي شيء.',
    howTo: ['الصق رمز JWT في مربع الرمز.', 'اقرأ الترويسة والحمولة مفكوكتين.', 'تحقق من حكم انتهاء الصلاحية.', 'أدخل سر HMAC اختياريًا للتحقق من التوقيع.'],
    faqs: [
      { q: 'هل يُرسَل رمزي إلى أي مكان؟', a: 'لا. فك التشفير حسابات محلية في متصفحك، وحتى التحقق من التوقيع يستخدم Web Crypto المحلي.' },
      { q: 'ما الخوارزميات القابلة للتحقق؟', a: 'HS256 وHS384 وHS512 بسر مشترك. أما RSA/ECDSA فيحتاج معالجة مفاتيح عامة خارج نطاق الأداة السريعة.' },
      { q: 'لماذا يقول "منتهي الصلاحية"؟', a: 'يُقارَن حقل exp بساعة جهازك. تحقق من ساعتك إذا بدا رمز جديد منتهيًا.' },
      { q: 'هل يمكنه إنشاء الرموز أو توقيعها؟', a: 'لا — فك وتدقيق فقط، وهذا يُبقي الأسرار خارج الصفحة.' },
    ],
  },
  'sql-formatter': {
    name: 'منسّق SQL',
    short: 'نسّق استعلامات SQL وصغّرها.',
    description: 'نسّق SQL مجانًا عبر الإنترنت. جمّل الاستعلامات بالمسافات البادئة وحالة الكلمات المفتاحية، أو صغّرها — فوريًا وبخصوصية داخل متصفحك.',
    intro: 'حوّل استعلامات SQL المكدسة في سطر واحد إلى نص مقروء. تنكسر الجُمل على أسطر مستقلة، وتنتظم الوصلات والشروط بمسافات واضحة حسب اختيارك لحالة الكلمات.',
    howTo: ['الصق استعلام SQL.', 'اختر حالة الكلمات المفتاحية وحجم المسافة.', 'اضغط تنسيق (أو تصغير لسطر واحد).', 'انسخ النتيجة أو حمّلها كملف .sql.'],
    faqs: [
      { q: 'هل يُرفع كود SQL؟', a: 'لا. التنسيق خوارزمية محلية صغيرة — ولا تغادر استعلاماتك التبويب.' },
      { q: 'هل النصوص والتعليقات آمنة؟', a: 'نعم. تُرمَّز النصوص والتعليقات أولًا فلا تُمس الكلمات داخلها أبدًا.' },
      { q: 'ما اللهجات المدعومة؟', a: 'SQL المعياري المشترك بين Postgres وMySQL وSQLite وSQL Server.' },
      { q: 'ماذا يفعل التصغير؟', a: 'يزيل التعليقات ويطوي المسافات في سطر واحد للتضمين أو السجلات.' },
    ],
  },
  'yaml-formatter': {
    name: 'منسّق YAML',
    short: 'تحقق من YAML ونسّقه وحوّله.',
    description: 'نسّق YAML مجانًا عبر الإنترنت. تحقق من الصياغة مع رسائل خطأ دقيقة، وأعد المسافات ورتّب المفاتيح وحوّل YAML إلى JSON — بخصوصية داخل متصفحك.',
    intro: 'أصلح ملفات إعدادات YAML المعطوبة بسرعة. تحقق مع مواقع أخطاء دقيقة، وأعد المسافات بانتظام، ورتّب المفاتيح لفروق نظيفة، أو حوّل مباشرة إلى JSON.',
    howTo: ['الصق محتوى YAML.', 'اختر حجم المسافة وترتيب المفاتيح اختياريًا.', 'اضغط تنسيق — أو تحويل إلى JSON.', 'انسخ الناتج أو حمّله.'],
    faqs: [
      { q: 'كيف تُعرَض الأخطاء؟', a: 'يعيد المحلل السطر والسبب بدقة، مثل سوء المسافة أو علامة جدولة ممنوعة في YAML.' },
      { q: 'هل يغيّر التنسيق بياناتي؟', a: 'لا. تتغير المسافات فقط (وترتيب المفاتيح اختياريًا)، وتبقى القيم مطابقة.' },
      { q: 'هل يحوّل YAML إلى JSON؟', a: 'نعم — بنقرة واحدة تحصل على JSON مكافئ بمسافة بادئة من مستويين.' },
      { q: 'هل تُرفع إعداداتي؟', a: 'أبدًا. التحليل يعمل محليًا في متصفحك.' },
    ],
  },
  'markdown-formatter': {
    name: 'منسّق Markdown',
    short: 'نسّق مستندات Markdown.',
    description: 'نسّق Markdown مجانًا عبر الإنترنت. وحّد العناوين والقوائم والتفاف النصوص بأداة Prettier — تعمل محليًا في متصفحك وتبقى ملفاتك خاصة.',
    intro: 'اجعل Markdown متناسقًا: قوائم موحدة وعناوين مرتبة ونصوص ملفوفة على عرض السطر الذي تختاره — بقوة Prettier التي تعمل بالكامل على جهازك.',
    howTo: ['الصق محتوى Markdown.', 'اختر عرض السطر وسلوك التفاف النصوص.', 'اضغط تنسيق.', 'انسخ النتيجة أو حمّلها كملف .md.'],
    faqs: [
      { q: 'ما الذي يُوحَّد؟', a: 'علامات القوائم وتباعد العناوين وأنماط التوكيد وأسوار الأكواد والتفاف الأسطر — نفس ناتج Prettier في المحررات.' },
      { q: 'هل يغيّر كلماتي؟', a: 'لا. يتغير التنسيق فقط ويبقى المحتوى النصي دون مساس.' },
      { q: 'ما التفاف النصوص؟', a: 'إعادة لف الفقرات الطويلة على عرض السطر، أو تركها كما هي، أو إبقاؤها في سطر واحد.' },
      { q: 'هل يُرفع مستندي؟', a: 'لا. تُحمَّل Prettier في متصفحك وتنسّق محليًا.' },
    ],
  },
};

for (const [slug, v] of Object.entries(TOOLS_EN)) setPath(en, `tools.${slug}`, v);
for (const [slug, v] of Object.entries(TOOLS_AR)) setPath(ar, `tools.${slug}`, v);

/* ------------------------------------------------------- other namespaces */

const MISC_EN = {
  'validation.imageTooLarge': 'This image is too large to process in the browser ({w} × {h} px). Try a smaller image, or resize it first.',
  'validation.heicFailed': 'This HEIC photo could not be converted on your device. Try exporting it as JPG from your iPhone (Settings → Camera → Formats → Most Compatible) and upload again.',
  'errors.signatureEmpty': 'No signature ink was detected. Try a sharper photo with darker ink, or lower the threshold.',
  'errors.ocrFailed': 'Text recognition failed for this file. Try a clearer, higher-contrast image.',
  'errors.ocrModelFailed': 'The OCR language files could not be downloaded. Check your internet connection and try again — your files never leave your device.',
  'errors.ocrTooLarge': 'This file is too large for on-device OCR. Try a smaller image (under 25 MB).',
  'errors.jwtInvalid': 'This does not look like a valid JWT. It should have three Base64URL parts separated by dots.',
  'errors.markdownSyntax': 'Markdown error: {message}',
  'errors.yamlParse': 'YAML error: {message}',
  'errors.yamlTooLarge': 'This YAML file is too large to format in the browser.',
  'errors.sqlTooLarge': 'This query exceeds the {max} in-browser limit.',
  'controls.targetSize': 'Target size',
  'controls.tolerance': 'Tolerance',
  'controls.feather': 'Edge softness',
  'controls.bgSource': 'Background colour',
  'controls.bgAuto': 'Auto-detect',
  'controls.bgWhite': 'Pure white',
  'controls.removeBg': 'Remove background',
  'controls.preset': 'Photo size',
  'controls.dpi': 'Print resolution',
  'controls.inkColor': 'Ink colour',
  'controls.threshold': 'Threshold',
  'controls.invertColors': 'Invert (light ink on dark background)',
  'controls.ocrLanguage': 'Text language',
  'exactKb.hitNote': 'Target hit — output is {size}.',
  'exactKb.missNote': 'The target could not be met. Smallest possible output is {size}.',
  'bgRemover.hint': 'Works best on solid backgrounds. Complex, multi-colour scenes need manual editing software.',
  'passport.preset_35x45': '35 × 45 mm — Passport (most countries)',
  'passport.preset_30x40': '30 × 40 mm — ID / visa',
  'passport.preset_33x48': '33 × 48 mm — ID photo',
  'passport.preset_50x50': '2 × 2 in (51 × 51 mm) — US visa',
  'passport.preset_40x60': '40 × 60 mm — ID photo',
  'passport.outputSize': 'Output: {w} × {h} px',
  'passport.make': 'Make photo',
  'signature.make': 'Make signature',
  'signature.hint': 'Photograph dark ink on plain white paper, in bright even light, for the cleanest cut-out.',
  'ocr.langEnglish': 'English',
  'ocr.langArabic': 'Arabic',
  'ocr.langBoth': 'English + Arabic',
  'ocr.start': 'Extract text',
  'ocr.extracting': 'Recognising text… {done} of {total}',
  'ocr.modelNote': 'The OCR engine downloads once (a few MB) and is cached. Your images are recognised on-device and never uploaded.',
  'ocr.noText': 'No text recognised',
  'ocr.resultTitle': 'Recognised text',
  'ocr.pageProgress': '{file} — page {done} of {total}',
  'ocr.pageLimitNote': 'To keep your browser fast and stable, OCR processes the first {max} pages of each document.',
  'jwt.tokenLabel': 'JWT token',
  'jwt.introHint': 'Paste a token above — its header and payload will be decoded instantly, offline.',
  'jwt.privacyNote': 'Tokens are decoded and verified entirely on your device. Nothing is transmitted anywhere.',
  'jwt.header': 'Header',
  'jwt.payload': 'Payload',
  'jwt.algorithm': 'Algorithm',
  'jwt.expires': 'Expires',
  'jwt.status': 'Status',
  'jwt.noExpiry': 'No expiry claim',
  'jwt.expired': 'Expired',
  'jwt.active': 'Active',
  'jwt.issuedAt': 'Issued at',
  'jwt.verifyTitle': 'Verify signature (HMAC)',
  'jwt.verifyHint': 'Enter the shared secret to verify HS256 / HS384 / HS512 signatures locally.',
  'jwt.secretPlaceholder': 'HMAC secret',
  'jwt.verifyAction': 'Verify',
  'jwt.validSig': 'Signature is valid for this secret.',
  'jwt.invalidSig': 'Signature does NOT match this secret.',
  'jwt.unsupportedAlg': 'Only HS256, HS384 and HS512 can be verified here.',
  'sql.keywordCase': 'Keyword case',
  'sql.preserve': 'Preserve',
  'sql.indent': 'Indentation',
  'sql.indent2': '2 spaces',
  'sql.indent4': '4 spaces',
  'sql.linesHint': '{before} lines before',
  'yaml.validYaml': 'Valid YAML',
  'yaml.sortKeys': 'Sort keys alphabetically',
  'yaml.toJson': 'Convert to JSON',
  'markdown.lineWidth': 'Line width',
  'markdown.proseWrap': 'Prose wrap',
  'markdown.wrapPreserve': 'Preserve',
  'markdown.wrapAlways': 'Wrap always',
  'markdown.wrapNever': 'Single line',
  'markdown.words': 'Words',
  'markdown.headings': 'Headings',
  'markdown.links': 'Links',
  'dev.options': 'Options',
  'pdfTools.extractTextAction': 'Extract text',
  'pdfTools.extractingText': 'Extracting text…',
  'pdfTools.toWordAction': 'Convert to Word',
  'pdfTools.toTextHint': 'Get every word out of your PDF as a clean, page-marked .txt file. Scanned pages need the PDF OCR tool instead.',
  'pdfTools.toWordHint': 'Turn PDF pages into editable Word (.doc) files with headings and page breaks. Text transfers cleanly; complex layouts do not.',
  'pdfTools.ocrHint': 'For scanned PDFs made of page images: each page is rendered and recognised on your device.',
  'pdfTools.lockedHint': 'Locked files were skipped — unlock them first with the PDF Unlock tool.',
  'pdfTools.noExtractableText': 'No extractable text was found. If this is a scanned PDF, try the PDF OCR tool instead.',
  'pdfTools.totalChars': 'Characters',
  'pdfTools.charsCount': '{count} characters',
  'guides.title': 'Image & PDF guides',
  'guides.subtitle': 'Practical, no-nonsense how-tos for the tasks people actually search for.',
  'guides.backToGuides': 'All guides',
  'guides.contents': 'In this guide',
  'guides.tryTool': 'Try the tool',
  'guides.relatedTools': 'Tools used in this guide',
  'guides.relatedGuides': 'Keep reading',
  'guides.readTime': '{n} min read',
};

const MISC_AR = {
  'validation.imageTooLarge': 'هذه الصورة كبيرة جدًا للمعالجة في المتصفح ({w} × {h} بكسل). جرّب صورة أصغر أو صغّرها أولًا.',
  'validation.heicFailed': 'تعذّر تحويل صورة HEIC على جهازك. جرّب تصديرها كـ JPG من الايفون (الإعدادات ← الكاميرا ← التنسيقات ← الأكثر توافقًا) ثم ارفعها مجددًا.',
  'errors.signatureEmpty': 'لم يُكتشَف أي حبر توقيع. جرّب صورة أوضح بحبر داكن، أو اخفض العتبة.',
  'errors.ocrFailed': 'فشل التعرّف على النص في هذا الملف. جرّب صورة أوضح وأعلى تباينًا.',
  'errors.ocrModelFailed': 'تعذّر تنزيل ملفات لغة OCR. تحقق من اتصالك بالإنترنت وحاول مجددًا — ملفاتك لا تغادر جهازك أبدًا.',
  'errors.ocrTooLarge': 'هذا الملف كبير جدًا للتعرّف على الجهاز. جرّب صورة أصغر (أقل من 25MB).',
  'errors.jwtInvalid': 'لا يبدو هذا رمز JWT صالحًا. يجب أن يتكون من ثلاثة أجزاء Base64URL تفصلها نقاط.',
  'errors.markdownSyntax': 'خطأ Markdown: {message}',
  'errors.yamlParse': 'خطأ YAML: {message}',
  'errors.yamlTooLarge': 'ملف YAML كبير جدًا للتنسيق في المتصفح.',
  'errors.sqlTooLarge': 'هذا الاستعلام يتجاوز حد {max} للمعالجة في المتصفح.',
  'controls.targetSize': 'الحجم المستهدف',
  'controls.tolerance': 'الحساسية',
  'controls.feather': 'نعومة الحواف',
  'controls.bgSource': 'لون الخلفية',
  'controls.bgAuto': 'تحديد تلقائي',
  'controls.bgWhite': 'أبيض نقي',
  'controls.removeBg': 'إزالة الخلفية',
  'controls.preset': 'مقاس الصورة',
  'controls.dpi': 'دقة الطباعة',
  'controls.inkColor': 'لون الحبر',
  'controls.threshold': 'العتبة',
  'controls.invertColors': 'عكس (حبر فاتح على خلفية داكنة)',
  'controls.ocrLanguage': 'لغة النص',
  'exactKb.hitNote': 'تحقق الهدف — الناتج {size}.',
  'exactKb.missNote': 'تعذّر بلوغ الهدف. أصغر ناتج ممكن هو {size}.',
  'bgRemover.hint': 'تعمل بأفضل شكل مع الخلفيات السادة. المشاهد المعقدة متعددة الألوان تحتاج برامج تحرير يدوية.',
  'passport.preset_35x45': '35 × 45 مم — جواز (معظم الدول)',
  'passport.preset_30x40': '30 × 40 مم — هوية / تأشيرة',
  'passport.preset_33x48': '33 × 48 مم — صورة هوية',
  'passport.preset_50x50': '2 × 2 إنش (51 × 51 مم) — تأشيرة أمريكا',
  'passport.preset_40x60': '40 × 60 مم — صورة هوية',
  'passport.outputSize': 'الناتج: {w} × {h} بكسل',
  'passport.make': 'إنشاء الصورة',
  'signature.make': 'إنشاء التوقيع',
  'signature.hint': 'صوّر حبرًا داكنًا على ورقة بيضاء سادة بإضاءة ساطعة متساوية للحصول على أنظف نتيجة.',
  'ocr.langEnglish': 'الإنجليزية',
  'ocr.langArabic': 'العربية',
  'ocr.langBoth': 'العربية + الإنجليزية',
  'ocr.start': 'استخراج النص',
  'ocr.extracting': 'جارٍ التعرّف على النص… {done} من {total}',
  'ocr.modelNote': 'يُنزَّل محرك OCR مرة واحدة (بضعة ميغابايت) ويُحفَظ. تُتعرَّف صورك على جهازك ولا تُرفَع أبدًا.',
  'ocr.noText': 'لم يُتعرَّف على نص',
  'ocr.resultTitle': 'النص المتعرَّف عليه',
  'ocr.pageProgress': '{file} — صفحة {done} من {total}',
  'ocr.pageLimitNote': 'للحفاظ على سرعة وثبات متصفحك، يعالج OCR أول {max} صفحة من كل مستند.',
  'jwt.tokenLabel': 'رمز JWT',
  'jwt.introHint': 'الصق رمزًا أعلاه — ستُفك ترويسته وحمولته فورًا دون اتصال.',
  'jwt.privacyNote': 'تُفك الرموز وتُتحقَّق بالكامل على جهازك. لا يُرسَل أي شيء إلى أي مكان.',
  'jwt.header': 'الترويسة',
  'jwt.payload': 'الحمولة',
  'jwt.algorithm': 'الخوارزمية',
  'jwt.expires': 'ينتهي في',
  'jwt.status': 'الحالة',
  'jwt.noExpiry': 'لا يوجد انتهاء',
  'jwt.expired': 'منتهي',
  'jwt.active': 'ساري',
  'jwt.issuedAt': 'أُصدِر في',
  'jwt.verifyTitle': 'التحقق من التوقيع (HMAC)',
  'jwt.verifyHint': 'أدخل السر المشترك للتحقق من تواقيع HS256 / HS384 / HS512 محليًا.',
  'jwt.secretPlaceholder': 'سر HMAC',
  'jwt.verifyAction': 'تحقق',
  'jwt.validSig': 'التوقيع صالح لهذا السر.',
  'jwt.invalidSig': 'التوقيع غير مطابق لهذا السر.',
  'jwt.unsupportedAlg': 'يمكن التحقق هنا من HS256 وHS384 وHS512 فقط.',
  'sql.keywordCase': 'حالة الكلمات المفتاحية',
  'sql.preserve': 'كما هي',
  'sql.indent': 'المسافة البادئة',
  'sql.indent2': 'مسافتان',
  'sql.indent4': '4 مسافات',
  'sql.linesHint': '{before} سطر قبل',
  'yaml.validYaml': 'YAML صالح',
  'yaml.sortKeys': 'ترتيب المفاتيح أبجديًا',
  'yaml.toJson': 'تحويل إلى JSON',
  'markdown.lineWidth': 'عرض السطر',
  'markdown.proseWrap': 'التفاف النصوص',
  'markdown.wrapPreserve': 'كما هي',
  'markdown.wrapAlways': 'التفاف دائم',
  'markdown.wrapNever': 'سطر واحد',
  'markdown.words': 'الكلمات',
  'markdown.headings': 'العناوين',
  'markdown.links': 'الروابط',
  'dev.options': 'خيارات',
  'pdfTools.extractTextAction': 'استخراج النص',
  'pdfTools.extractingText': 'جارٍ استخراج النص…',
  'pdfTools.toWordAction': 'تحويل إلى Word',
  'pdfTools.toTextHint': 'استخرج كل كلمات PDF في ملف .txt نظيف مع علامات الصفحات. الصفحات الممسوحة تحتاج أداة OCR بدلًا من ذلك.',
  'pdfTools.toWordHint': 'حوّل صفحات PDF إلى ملفات Word (.doc) قابلة للتحرير مع العناوين وفواصل الصفحات. ينتقل النص بوضوح دون التخطيطات المعقدة.',
  'pdfTools.ocrHint': 'لملفات PDF الممسوحة المكوّنة من صور الصفحات: تُعرَض كل صفحة ويُتعرَّف عليها على جهازك.',
  'pdfTools.lockedHint': 'تُجوهِلت الملفات المقفلة — أزل حمايتها أولًا بأداة فك حماية PDF.',
  'pdfTools.noExtractableText': 'لم يُعثَر على نص قابل للاستخراج. إذا كان ملفًا ممسوحًا فجرّب أداة OCR لملفات PDF.',
  'pdfTools.totalChars': 'الأحرف',
  'pdfTools.charsCount': '{count} حرف',
  'guides.title': 'أدلة الصور وPDF',
  'guides.subtitle': 'شروحات عملية مباشرة للمهام التي يبحث عنها الناس فعلًا.',
  'guides.backToGuides': 'كل الأدلة',
  'guides.contents': 'في هذا الدليل',
  'guides.tryTool': 'جرّب الأداة',
  'guides.relatedTools': 'الأدوات المستخدمة في هذا الدليل',
  'guides.relatedGuides': 'تابع القراءة',
  'guides.readTime': '{n} دقائق قراءة',
};

for (const [k, v] of Object.entries(MISC_EN)) setPath(en, k, v);
for (const [k, v] of Object.entries(MISC_AR)) setPath(ar, k, v);

/* ------------------------------------------------- refresh stale numbers */

const REFRESH_EN = {
  'home.searchSubtitle': 'Search every free tool',
  'home.searchTitle': 'What do you want to do today?',
  'home.allToolsSubtitle': 'Every tool, free forever. No accounts, no watermarks, no limits.',
  'toolsPage.title': 'All free tools',
  'toolsPage.subtitle': 'Every tool runs entirely in your browser — compress, resize, convert, edit, plus PDF, text and developer utilities. No uploads, no sign-up.',
  'seo.toolsTitle': 'All Free Online Tools — Image, PDF, Text & Developer Utilities | Piclizer',
  'seo.toolsDescription': 'Explore every free Piclizer tool: compress images to exact sizes, convert iPhone HEIC photos, edit PDFs, extract text with OCR, format code and more. 100% in your browser.',
  'seo.homeDescription': 'Free online tools that run 100% in your browser. Compress images, convert iPhone HEIC photos, edit PDFs, extract text and format code — no upload, no sign-up, private by design.',
  'footer.description': 'Free online tools that run entirely in your browser. Compress images, convert HEIC photos, edit PDFs and format code without uploading anything anywhere.',
};

const REFRESH_AR = {
  'home.searchSubtitle': 'ابحث في كل الأدوات المجانية',
  'home.searchTitle': 'ماذا تريد أن تفعل اليوم؟',
  'home.allToolsSubtitle': 'كل الأدوات مجانية للأبد. دون حسابات أو علامات مائية أو حدود.',
  'toolsPage.title': 'كل الأدوات المجانية',
  'toolsPage.subtitle': 'كل أداة تعمل بالكامل داخل متصفحك — ضغط وتصغير وتحويل وتحرير، إضافة لأدوات PDF والنصوص والمطورين. دون رفع أو تسجيل.',
  'seo.toolsTitle': 'كل الأدوات المجانية — صور وPDF ونصوص وأدوات مطورين | Piclizer',
  'seo.toolsDescription': 'اكتشف كل أدوات Piclizer المجانية: اضغط الصور لأحجام دقيقة، وحوّل صور الايفون HEIC، وحرّر PDF، واستخرج النصوص، ونسّق الأكواد — كل ذلك داخل متصفحك.',
  'seo.homeDescription': 'أدوات مجانية تعمل 100% داخل متصفحك. اضغط الصور وحوّل صور الايفون HEIC وحرّر PDF واستخرج النصوص ونسّق الأكواد — دون رفع أو تسجيل وبخصوصية تامة.',
  'footer.description': 'أدوات مجانية تعمل بالكامل داخل متصفحك. اضغط الصور وحوّل صور HEIC وحرّر PDF ونسّق الأكواد دون رفع أي شيء إلى أي مكان.',
};

for (const [k, v] of Object.entries(REFRESH_EN)) setPath(en, k, v);
for (const [k, v] of Object.entries(REFRESH_AR)) setPath(ar, k, v);

// homeFaqs first answer mentions the old tool count.
if (Array.isArray(en.homeFaqs) && en.homeFaqs[0]) {
  en.homeFaqs[0].a = 'Yes. Every tool is completely free with no usage limits, no watermarks and no hidden fees.';
}
if (Array.isArray(ar.homeFaqs) && ar.homeFaqs[0]) {
  ar.homeFaqs[0].a = 'نعم. كل أداة مجانية تمامًا دون حدود استخدام أو علامات مائية أو رسوم خفية.';
}

writeFileSync(EN, `${JSON.stringify(en, null, 2)}\n`);
writeFileSync(AR, `${JSON.stringify(ar, null, 2)}\n`);
console.log('messages updated');
